apiVersion: v1
kind: Secret
metadata:
  name: collector-db-secret
  namespace: data
type: Opaque
stringData:
  #DATABASE_URL: postgresql://fullcount_user:fullcount_pass@postgresql-service.db.svc.cluster.local:5432/fullcount
  DATABASE_URL: CHANGE_ME
  #JWT_ACCESS_SECRET: "any-secret-key-1"
  #JWT_REFRESH_SECRET: "any-secret-key-2"
