apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  MLB_API_BASE_URL: "https://statsapi.mlb.com/api/v1"
  COLLECTOR_INTERVAL: "300"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgresql-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "fullcount"