apiVersion: v1
kind: ConfigMap
metadata:
  name: fullcount-config
  namespace: app
  labels:
    app.kubernetes.io/name: full-count-api
    app.kubernetes.io/part-of: full-count
data:
  PORT: "3000"
  REDIS_HOST: "redis.data.svc.cluster.local"
  REDIS_PORT: "6379"
