apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
stringData:
  POSTGRES_DB: fullcount
  POSTGRES_USER: fullcount_user
  POSTGRES_PASSWORD: fullcount_pass
  DATABASE_URL: postgresql://fullcount_user:fullcount_pass@postgresql-service:5432/fullcount